include: config/algorithm/ppo_base.yaml

n_steps: 20
batch_size: 50
n_epochs: 20
alg_seed: 42
total_source_timesteps: 100000
n_stream: 100
source_lr: 0.0003
n_process: 8
on_policy_threshold: 0.7
compression_window: 10